import React, { useState, useMemo } from 'react';
import { Copy, Check, Download, Bot, Plus, Trash2, Sparkles, ShieldCheck } from 'lucide-react';

interface BotRule {
  name: string;
  agent: string;
  allowed: boolean;
}

export const RobotsTxtGeneratorTool: React.FC = () => {
  const [bots, setBots] = useState<BotRule[]>([
    { name: 'Googlebot (Google Search)', agent: 'Googlebot', allowed: true },
    { name: 'Googlebot-Image', agent: 'Googlebot-Image', allowed: true },
    { name: 'Bingbot (Microsoft Bing)', agent: 'Bingbot', allowed: true },
    { name: 'DuckDuckBot', agent: 'DuckDuckBot', allowed: true },
    { name: 'Baiduspider', agent: 'Baiduspider', allowed: true },
    { name: 'YandexBot', agent: 'YandexBot', allowed: true },
    { name: 'GPTBot (OpenAI AI Web Crawler)', agent: 'GPTBot', allowed: false },
    { name: 'CCBot (Common Crawl AI Dataset)', agent: 'CCBot', allowed: false },
  ]);

  const [disallowPaths, setDisallowPaths] = useState<string[]>([
    '/admin',
    '/private/',
    '/api/',
    '/checkout',
    '/search',
  ]);
  const [newPath, setNewPath] = useState<string>('');
  const [crawlDelay, setCrawlDelay] = useState<string>('none');
  const [sitemapUrl, setSitemapUrl] = useState<string>('https://mentorarena.online/sitemap.xml');
  const [copied, setCopied] = useState<boolean>(false);

  const toggleBot = (idx: number) => {
    setBots(prev => {
      const next = [...prev];
      next[idx].allowed = !next[idx].allowed;
      return next;
    });
  };

  const handleAddPath = () => {
    if (!newPath.trim()) return;
    let clean = newPath.trim();
    if (!clean.startsWith('/')) clean = '/' + clean;
    if (!disallowPaths.includes(clean)) {
      setDisallowPaths(prev => [...prev, clean]);
    }
    setNewPath('');
  };

  const handleRemovePath = (pathToRemove: string) => {
    setDisallowPaths(prev => prev.filter(p => p !== pathToRemove));
  };

  const generatedRobots = useMemo(() => {
    let out = `# robots.txt generated by Mentor Arena SEO Webmaster Tools\n`;
    out += `# Date: ${new Date().toISOString().split('T')[0]}\n\n`;

    // Global default
    out += `User-agent: *\n`;
    out += `Allow: /\n`;
    disallowPaths.forEach(path => {
      out += `Disallow: ${path}\n`;
    });
    if (crawlDelay !== 'none') {
      out += `Crawl-delay: ${crawlDelay}\n`;
    }
    out += `\n`;

    // Specific bots rules
    bots.forEach(b => {
      if (!b.allowed) {
        out += `# Disallow ${b.name}\n`;
        out += `User-agent: ${b.agent}\n`;
        out += `Disallow: /\n\n`;
      }
    });

    if (sitemapUrl.trim()) {
      out += `# XML Sitemap Directive\n`;
      out += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    return out;
  }, [bots, disallowPaths, crawlDelay, sitemapUrl]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedRobots);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedRobots], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Settings Column (7 cols) */}
        <div className="lg:col-span-7 bg-white p-6 sm:p-8 rounded-3xl border border-gray-200/80 shadow-sm space-y-6">
          <h3 className="text-lg font-bold text-gray-900">Robots.txt Directives</h3>

          {/* Crawler Permissions */}
          <div className="space-y-3">
            <label className="block text-xs font-bold uppercase tracking-wider text-gray-500">
              Bot & Crawler Permissions
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {bots.map((b, idx) => (
                <div
                  key={b.agent}
                  onClick={() => toggleBot(idx)}
                  className={`p-3 rounded-2xl border flex items-center justify-between cursor-pointer transition-all ${
                    b.allowed
                      ? 'bg-emerald-50/50 border-emerald-200 text-emerald-900'
                      : 'bg-rose-50/50 border-rose-200 text-rose-900'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <Bot size={15} className={b.allowed ? 'text-emerald-600' : 'text-rose-600'} />
                    <span className="text-xs font-semibold">{b.name}</span>
                  </div>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                    b.allowed ? 'bg-emerald-200/60 text-emerald-800' : 'bg-rose-200/60 text-rose-800'
                  }`}>
                    {b.allowed ? 'Allow' : 'Block'}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Disallow Paths */}
          <div className="space-y-3">
            <label className="block text-xs font-bold uppercase tracking-wider text-gray-500">
              Restricted Disallow Directories
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={newPath}
                onChange={(e) => setNewPath(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAddPath()}
                placeholder="/admin, /staging, /temp..."
                className="flex-1 px-4 py-2 rounded-xl bg-gray-50 border border-gray-200 text-xs focus:bg-white focus:ring-2 focus:ring-brand-blue/20 outline-none font-mono"
              />
              <button
                onClick={handleAddPath}
                className="px-4 py-2 bg-brand-blue text-white rounded-xl text-xs font-bold hover:bg-brand-blue/90 flex items-center gap-1 cursor-pointer"
              >
                <Plus size={14} /> Add Path
              </button>
            </div>

            <div className="flex flex-wrap gap-2 pt-2">
              {disallowPaths.map(p => (
                <span
                  key={p}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-gray-100 text-gray-700 text-xs font-mono font-medium border border-gray-200"
                >
                  {p}
                  <button
                    onClick={() => handleRemovePath(p)}
                    className="text-gray-400 hover:text-red-500 transition-colors"
                  >
                    <Trash2 size={12} />
                  </button>
                </span>
              ))}
            </div>
          </div>

          {/* Sitemap URL & Crawl Delay */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-gray-700 mb-1">Crawl Delay (Seconds)</label>
              <select
                value={crawlDelay}
                onChange={(e) => setCrawlDelay(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-gray-50 border border-gray-200 text-xs focus:bg-white focus:ring-2 focus:ring-brand-blue/20 outline-none"
              >
                <option value="none">No Delay (Default)</option>
                <option value="5">5 Seconds</option>
                <option value="10">10 Seconds</option>
                <option value="20">20 Seconds</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-700 mb-1">XML Sitemap Location</label>
              <input
                type="url"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="https://example.com/sitemap.xml"
                className="w-full px-3 py-2 rounded-xl bg-gray-50 border border-gray-200 text-xs focus:bg-white focus:ring-2 focus:ring-brand-blue/20 outline-none font-mono"
              />
            </div>
          </div>
        </div>

        {/* Live Output Column (5 cols) */}
        <div className="lg:col-span-5 bg-zinc-950 text-white p-6 sm:p-8 rounded-3xl border border-zinc-800 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center justify-between border-b border-zinc-850 pb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-emerald-400 font-mono">
                Generated robots.txt Preview
              </span>
              <span className="text-[11px] text-zinc-500 font-mono">UTF-8 Plaintext</span>
            </div>

            <pre className="p-4 rounded-2xl bg-zinc-900/90 text-zinc-300 text-xs font-mono overflow-x-auto leading-relaxed border border-zinc-800 selection:bg-emerald-500/20 max-h-[380px]">
              <code>{generatedRobots}</code>
            </pre>
          </div>

          <div className="flex items-center gap-3 pt-4 border-t border-zinc-850">
            <button
              onClick={handleCopy}
              className="flex-1 py-3 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-zinc-950 font-bold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer shadow-md"
            >
              {copied ? <Check size={15} /> : <Copy size={15} />}
              {copied ? 'Copied robots.txt' : 'Copy File Content'}
            </button>
            <button
              onClick={handleDownload}
              className="py-3 px-5 rounded-xl bg-zinc-800 hover:bg-zinc-750 text-zinc-200 font-bold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer border border-zinc-700"
            >
              <Download size={15} /> Download
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
